# fly.toml app configuration file generated for news-post-checker-backend on 2024-02-05T08:45:51-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'news-post-checker-backend'
primary_region = 'sjc'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
